BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py - http://git.io/lLljaA
BEGIN:VEVENT
DESCRIPTION:https://transportnsw.info/alerts/details#/ems-78211\n\nSaturday 26 and Sunday 27 September\nBuses replace trains between Bomaderry and Wollongong.\nTrains run between Port Kembla\, Wollongong and Bondi Junction\, some to a changed timetable.\nBuses do not run to the train timetable. If connecting with trains at Wollongong you may need to catch an earlier bus to ensure you meet your train connection.\nSydney Metro trackwork may affect how you travel. Metro services do not run between Sydenham and Chatswood.\nUse trains between Central and Epping or Chatswood.
DTEND:20260927T135925Z
DTSTART:20260925T160000Z
SUMMARY:Buses replace trains between Bomaderry and Wollongong
UID:458650b8-76af-5f3c-b00c-a3a2e2d130be
URL:https://transportnsw.info/alerts/details#/ems-78211
END:VEVENT
BEGIN:VEVENT
DESCRIPTION:https://transportnsw.info/alerts/details#/ems-78209\n\nFriday 25 September\nFrom 2:50PM\, buses replace trains from Wollongong to Bomaderry.\nFrom 3:50PM\, buses replace trains from Bomaderry to Wollongong.\nTrains run between Port Kembla\, Wollongong and Bondi Junction\, some to a changed timetable.\nBuses do not run to the train timetable. If connecting with trains at Wollongong you may need to catch an earlier bus to ensure you meet your train connection.
DTEND:20260925T160044Z
DTSTART:20260925T045000Z
SUMMARY:Buses replace trains between Bomaderry and Wollongong
UID:9f75f272-9f9e-5380-9282-df94e8dd6ffa
URL:https://transportnsw.info/alerts/details#/ems-78209
END:VEVENT
END:VCALENDAR