BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py - http://git.io/lLljaA
BEGIN:VEVENT
DESCRIPTION:https://transportnsw.info/alerts/details#/ems-74851\n\nOn Sunday 26 July\, from 2.20AM to 11.50AM\, buses replace trains between Bomaderry\, Port Kembla and Wollongong.
DTEND:20260726T015000Z
DTSTART:20260725T162059Z
SUMMARY:Buses replace trains between Bomaderry\, Port Kembla and Wollongong
UID:4087c5d1-5e20-5d18-9087-c4dc2317772d
URL:https://transportnsw.info/alerts/details#/ems-74851
END:VEVENT
BEGIN:VEVENT
DESCRIPTION:https://transportnsw.info/alerts/details#/ems-74849\n\nOn Saturday 25 July\, from 3AM to 11AM\, buses replace trains between Dapto\, Port Kembla and Sutherland.\nTrains run to a changed timetable between Bomaderry\, Kiama and Dapto\, and T4 Eastern Suburbs & Illawarra Line trains run between Sutherland and Bondi Junction.
DTEND:20260725T010000Z
DTSTART:20260724T170008Z
SUMMARY:Buses replace trains between Dapto\, Port Kembla and Sutherland
UID:acee4a0d-781e-5fa9-a42a-28ba83804969
URL:https://transportnsw.info/alerts/details#/ems-74849
END:VEVENT
END:VCALENDAR