BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py - http://git.io/lLljaA
BEGIN:VEVENT
DESCRIPTION:https://transportnsw.info/alerts/details#/ems-74851\n\nOn Sunday 26 July\, from 2.20AM to 11.50AM\, buses replace trains between Bomaderry\, Port Kembla and Wollongong.
DTEND:20260726T015000Z
DTSTART:20260725T162059Z
SUMMARY:Buses replace trains between Bomaderry\, Port Kembla and Wollongong
UID:4087c5d1-5e20-5d18-9087-c4dc2317772d
URL:https://transportnsw.info/alerts/details#/ems-74851
END:VEVENT
END:VCALENDAR